# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"config_file_path": "TSXCore.ipynb",
         "f": "TSXCore.ipynb",
         "config": "TSXCore.ipynb",
         "create_tsx_features": "TSXCore.ipynb"}

modules = ["config.py",
           "TSX_preprocessing.py"]

doc_url = "https://byz007.github.io/helpseeker_tsx/"

git_url = "https://github.com/byz007/helpseeker_tsx/tree/master/"

def custom_doc_links(name): return None
